### ISSUE TITLE
[UX] Remove up/down arrows in parameters

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-ui#146]
UX Feedback  : 

The small up/down arrows that appear when selecting a parameter are not useful (we do not change these parameters by +1 / -1) . Can they be removed ? 

![image](https://user-images.githubusercontent.com/16088743/103351248-e4e06280-4aa2-11eb-8356-b9eeb8b61dd6.png)

**Comment by suzil** [comment]
Yeah, I noticed that before. Probably we can fix it with CSS: https://stackoverflow.com/a/50824080
