### ISSUE TITLE
[UX] Allow vertical zoom in plot

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-ui#152]
Currently it is not possible to zoom vertically in the main plot window. This makes it hard to distinguish small lines. 

- would be nice to be able to use a rectangular zoom in the main zoom window
- it would be even nicer to have the bottom figure remain on full scale (vertically), so that you keep a constant reminder of where the main lines are.

**Comment by suzil** [comment]
> would be nice to be able to use a rectangular zoom in the main zoom window

Just did a super quick check, and it seems like it should be possible if we set `fixedrange: false` on the Plotly yaxis layout.

https://user-images.githubusercontent.com/13723264/103370600-d38f5a00-4a92-11eb-92ca-35e098de23bf.mov

Will need to investigate how to keep the bottom figure remain at the same scale.

**Comment by erwanp** [comment]
Nice, well done !
