### ISSUE TITLE
Deployed RADIS UI is failing

### ISSUE THREAD

**Issue by suzil** [suzil/radis-ui#176]
![Screen Shot 2021-01-08 at 4 56 51 PM](https://user-images.githubusercontent.com/13723264/104073154-8e75d100-51d2-11eb-9b23-64312a01b833.png)

**Comment by erwanp** [comment]
For information and as mentioned on Slack  : 

As of today https://radis.app works on Firefox, and fails on Brave (Chromium based). I hadn't tried Firefox before so I don't know if something changed. It's possible it was working from the start :slightly_smiling_face:

And it works very well actually !! Here the asymmetric strech band of HITRAN CO2 calculated with RADIS-app (still on Heroku with 500 Mb RAM) and Spectraplot (on Amazon EC2), same conditions (including wstep as 0.01 is the default in #radis-app ):
https://user-images.githubusercontent.com/16088743/104090673-9ee08700-5278-11eb-854a-bd683753895d.gif
Had the time to download the database, cache it, and plot 4 spectra before Spectraplot crashed 💪 


Point : you should mention the Browser in the error title.

**Comment by suzil** [comment]
I was running this on Chrome. It was a bit strange because it works locally but not deployed. I found out my adblock extension was blocking the request 🙈  Maybe Brave is doing something similar with blocking the request?

The current deployment is not really production-grade but just something I put together quickly, so I'd imagine this will be fixed with a proper setup. I'm going to close this for now and we can revisit when changing the deployment from Heroku to EC2 (https://github.com/suzil/radis-ui/issues/175).
