### ISSUE TITLE
Deployed RADIS-ui failing on Brave Browser

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-ui#177]
See also #176 

![image](https://user-images.githubusercontent.com/16088743/104091046-31822580-527b-11eb-9485-6d902ab62775.png)

But I've no idea which information I should provide to help !

**Comment by erwanp** [comment]
Fixed by turning Brave Shield down (adblock etc.). The interesting part is that now it works, even with shield back up, even in a new private session !

**Comment by suzil** [comment]
Yup, I encountered a similar issue with my adblock extension: https://github.com/suzil/radis-ui/issues/176#issuecomment-757348367

Will likely be fixed by setting up a proper production deployment instead of what I just quickly put together.

**Comment by suzil** [comment]
@erwanp I made some changes and it seems to work for me now even with adblock enabled. Does it work now for you?

**Comment by erwanp** [comment]
Fixed here at least in 686da99

**Comment by suzil** [comment]
Yay
