### ISSUE TITLE
Select molecule with keyboard doesnt work

### ISSUE THREAD

**Issue by erwanp** [suzil/radis-ui#185]
Small bug : 

2 attempts in this small video : 

Select molecule (ex : H2O) with keyboard while the previous molecule is already here (CO) : 
- typing and searching the molecule name (up/down keys) from keyboard works well ! 
- but by pressing Enter the molecule field is emptied and we get the error message "Molecule must be defined"

Same if no molecule was initially given
- by pressing Enter the new molecule displays correctly in the input box, but is not taken into account and we get the error message "Molecule must be defined"

![press-enter](https://user-images.githubusercontent.com/16088743/104125616-38329a80-5358-11eb-9177-36239274064c.gif)

**Comment by minouHub** [comment]
It is working now, you close the issue @erwanp
