### ISSUE TITLE
Charging indefinitely 

### ISSUE THREAD

**Issue by minouHub** [suzil/radis-ui#189]
Hello,

Thank you for working on this amazing code! I wrote this issue to notify that the app is yet not working at the address https://www.radis.app/

- Detail of the bug: try to run the code after loading the page and the calculation is ongoing forever
- Using Windows10 and Mozilla

Minou

https://user-images.githubusercontent.com/36677294/104223321-c5065280-5443-11eb-92f0-910b3b82b6da.mp4

**Comment by erwanp** [comment]
I hold my word. Bug reported, you get a 🥐!

**Comment by erwanp** [comment]
Probably related to #177 too, although it used to work on Firefox. Good to have new data !

**Comment by erwanp** [comment]
I think @suzil fixed this, can you retry when you have the time?

**Comment by minouHub** [comment]
Alright. Well done @suzil !
